services:
  discord-bot:
    build: .
    container_name: canis_ultima_bot
    restart: always
    volumes:
      # Collega il file dello storico tra la tua macchina e il container
      # In questo modo, se spegni il container, i dati restano sul tuo PC
      - ./storico_match.json:/app/storico_match.json